### ISSUE TITLE
i18n for zksync docs

### ISSUE THREAD

**Issue by WillXing** [matter-labs/zksync-lite-docs#61]
In order to help more developer get to know zksync, involves in the eco-system and contribute. Will be beneficial to developers and zksync both to make zksync docs have multiple language options.

🧾 Expected Behaviour

Have i18n configured in the project, and have multiple languages options.

🔨 Current Behaviour

zksync docs only have an English version.

## ✅ Acceptance criteria

- User able to choose a different language for zksync docs
- Chinese version of docs

**Comment by WillXing** [comment]
We can be working on the configuration and translate the current docs we have.

**Comment by SuccinctPaul** [comment]
Hi,  @WillXing  , we are going to translate the zkSync 2.0 docs into Chinese. If you are interested, welcome for your join.
Here is the [repo]( https://github.com/ChengYueJia/zkSync-v2-docs-zh.). 
Waiting for you pr.
