### ISSUE TITLE
RaidGuild Request: indexed.wtf doc edits and additions

### ISSUE THREAD

**Issue by kittyslasher** [matter-labs/zksync-lite-docs#63]
Hello blessed devs,
@dvush @gluk64 @ly0va @popzxc @shamatar @slumber @vladbochok 

We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically. Having easily accessible information about all these solutions will bring more attention to your project.

Please find the markdown for the docs for your project below.

Kindly review, edit and provide any missing details and information at your taste and discretion as project leaders.

Moving forward we aim to keep indexed.wtf as current and beneficial to developers researching the ecosystem as possible. Please feel free at any time to submit an issue or PR to update the displayed information.

Thank you for your attention to this matter.

Best,
The Indexed Army
We stand for accurate data.

www.RaidGuild.org
@chair28980 @kittyslasher

```markdown

# Matter Labs

## Description

<!-- Please update description if necessary. Please feel free to update/eliminate/include headers below.-->

zkSync (built by Matter Labs) is a scaling and privacy engine for Ethereum. Its current functionality scope includes low gas transfers of ETH and ERC20 tokens in the Ethereum network. This document is a high-level description of the zkSync development ecosystem.

## Consensus Type


## Tx Cost


## Average TPS

##Finality Time

## Governance/validator Token

## Transactional Token

## Resources

[Website](https://matter-labs.io/)

[Github](https://github.com/matter-labs)

[Developer Docs]()

## Social Media & Community

[Telegram](https://t.me/matterlabs)

[Twitter](https://twitter.com/the_matter_labs)

[Medium](https://medium.com/matter-labs)

[Gitter](https://gitter.im/matter-labs/community)


```

**Comment by StanislavBreadless** [comment]
Hi @kittyslasher !

Should we make a PR here:
https://github.com/raid-guild/indexed/blob/main/docs/matter-labs-doc.md

or simply reply to your comment with the description?

Also, we would suggest to use "zkSync", because the Matter Labs is the company behind it, but not the scaling solution itself :slightly_smiling_face:

**Comment by kittyslasher** [comment]
> Hi @kittyslasher !
> 
> Should we make a PR here:
> https://github.com/raid-guild/indexed/blob/main/docs/matter-labs-doc.md
> 
> or simply reply to your comment with the description?
> 
> Also, we would suggest to use "zkSync", because the Matter Labs is the company behind it, but not the scaling solution itself 🙂

First off you hacky hacker get out of our repo! Jk Jk Right now we simply ask you just fill out the template with the description and other requested information. Feel free to add additional links to the bottom or information you feel is important to the project. After we make this initial update we will ask you keep the docs updated make any necessary PR's to do so!

Second we apologize on the name mis-happening this is one reason we are reaching out to the project we want to ensure we represent the company properly!

Last I appreciate the prompt and professional response. We look forward to helping your project grow! 🚀 🌔

**Comment by kittyslasher** [comment]
@StanislavBreadless @keriat 

Good morning/Afternoon Depending on your time zone. We plan on launching the site within the next week and are still awaiting updated docs.

**Comment by StanislavBreadless** [comment]
Hi @kittyslasher !

Sorry for the late reply :( The last two weeks have been very intense for our team

One question: 
What should we write in the `## Transactional` subheader?

**Comment by kittyslasher** [comment]
> Hi @kittyslasher !
> 
> Sorry for the late reply :( The last two weeks have been very intense for our team
> 
> One question:
> What should we write in the `## Transactional` subheader?

No worries I understand as things have been crazy here! I'm noticing the template got cut off when copying it. This is my fault and I apologize.

I went ahead and updated the original post. It should have said transactional Token.

**Comment by StanislavBreadless** [comment]
I hope we will be able to update the docs since the NFTs and atomic swaps/limit orders will be ready very soon :slightly_smiling_face:.

```markdown
# zkSync

## Description

zkSync (built by Matter Labs) is a scaling and privacy engine for Ethereum. Its current functionality scope includes low gas transfers of ETH and ERC20 tokens in the Ethereum network. 

zkSync 1.0 (the current version) will support NFTs and limited orders this spring. 
zkSync 2.0 (testnet in May, mainnet in August) will bring full EVM support.

## Consensus Type

PoS, under development

## Tx Cost

600 gas (the users will be able to go with ~$0.01 when zkPorter is released)

## Average TPS

2000

## Finality Time

5 minutes

## Governance/validator Token

Under development.

## Transactional Token

ETH, ERC20 tokens. NFTs soon.

## Resources

[Website](https://zksync.io/)

[Github](https://github.com/matter-labs/zksync)

[Developer Docs](https://zksync.io/dev/)

## Social Media & Community

[Telegram](https://t.me/zksync)

[Twitter](https://twitter.com/zksync)

[Medium](https://medium.com/matter-labs)

[Gitter](https://gitter.im/matter-labs/zksync)

```

**Comment by kittyslasher** [comment]
We are looking to launch this by this coming Sunday. We will be allowing changes and updates to the docs once pushed. We are discussing what will be the easiest method to keep them updated once we go live. I much appreciate the efforts in getting these completed and I look forward to watching the project grow!  NFT and Atomic swaps!?! Oh my!
